databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh.Host=host.docker.internal
databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh.Password=N2Fb2iEZqaWm2snaHUs8swXjqq5t51RK+3NLYGN2yoEzEAAefYpL8JVwG49ClrnxaPw2+dyPbBW+hH3i8ktuTIzy8Wu3tf91bxQDMbNfzAHbCP6Ux0TUYbM55YA38JaCDZWTDA7tKX7FxuTimQ3+OA\=\=
databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh.Password.encrypted=ENCRYPTED
databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh.Port=22
databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh.User=example_user
