databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh_key.Host=host.docker.internal
databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh_key.Key\ file.ROUTE.LOCAL.PATH=/mnt/IK/.ssh/denodo_ssh_key
databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh_key.Passphrase=2SqpJnOe9nUZd9NEEiiuUqpBWRoJPZyf+DfrphAThZXARe538FKhKk2/L/DZekSAdHDkYUPU/5OkrCduwPXRXxFFD6qDsOffF1ZMgrseTo2ZiwqCFYRnWseoQYvpZlMh
databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh_key.Passphrase.encrypted=ENCRYPTED
databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh_key.Port=22
databases.http.folder.connectivity.folder.data\ sources.datasources.custom.ds_ssh_key.User=ikemonsoayika
