databases.postgres.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_denodo.DATABASEURI=jdbc\:postgresql\://host.docker.internal\:5432/DENODO_DATA
databases.postgres.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_denodo.TARGET_SCHEMA=DUMMY
databases.postgres.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_denodo.USERNAME=postgres
databases.postgres.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_denodo.USERPASSWORD=Wx4hdQ+IGe3GeOB6Lhzemny6dBh5tY0YKH14l92pe67MIz9oFho9whsuO5cnNmjsnEymZpFXpjcLnKtX12ZiS25ALxINPqHnd8+zUFIXY7a7k2tVGvdBWPqzTCP0IAoC
databases.postgres.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_denodo.USERPASSWORD.ENCRYPTED=ENCRYPTED
