databases.mysql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_mysql.DATABASEURI=jdbc\:mysql\://host.docker.internal\:3306
databases.mysql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_mysql.USERNAME=root
databases.mysql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_mysql.USERPASSWORD=vxUj6h/F8Dfwm9WOaCNKHOgsR72OobCtor0pg8pstJoWWtPJGRqQOY8Ig3ge5SwHtwId+nWoQPMfG3IYo3bUEWJeKXo5fjuqNrldNDJjQ4UpzpeTqhoE+JXqJ9bS+uSS
databases.mysql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_mysql.USERPASSWORD.ENCRYPTED=ENCRYPTED
