databases.query_acceleration.folder.logs\ information.folder.connections.folder.local\ files.views.custom.bv_request_notification_file.Filepath.ROUTE.LOCAL.PATH=@{LOGS_PATH}/@{LOG_PREFIX}-queries.log
