databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_bakehouse_sales_franchises.CATALOGNAME=samples
databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_bakehouse_sales_franchises.SCHEMANAME=bakehouse
