databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_bakehouse_media_customer_reviews.CATALOGNAME=samples
databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_bakehouse_media_customer_reviews.SCHEMANAME=bakehouse
