databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_bakehouse_sales_suppliers.CATALOGNAME=samples
databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_bakehouse_sales_suppliers.SCHEMANAME=bakehouse
