databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_bakehouse_media_gold_reviews_chunked.CATALOGNAME=samples
databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_bakehouse_media_gold_reviews_chunked.SCHEMANAME=bakehouse
