databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_wonderbricks_hosts.CATALOGNAME=samples
databases.sql.folder.connectivity.folder.base\ views.folder.databricks.views.jdbc.bv_wonderbricks_hosts.SCHEMANAME=wanderbricks
