databases.sql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_mysql.DATABASEURI=jdbc\:mysql\://host.docker.internal\:3306
databases.sql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_mysql.USERNAME=root
databases.sql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_mysql.USERPASSWORD=Aajmr8x29hpdxuL/p++eA63mCIPisMYn12qOa/Ke4efrjSJjhmry/tM/9ZyswelwJXRapIBlQiRQjxt+BzGggI/4pvL6Q0MbhgvL2E1Sd5ppAPjTcrkkyZQcRWUDC/XK
databases.sql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_mysql.USERPASSWORD.ENCRYPTED=ENCRYPTED
