databases.sql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_postgresql.DATABASEURI=jdbc\:postgresql\://host.docker.internal\:5432/DENODO_DATA
databases.sql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_postgresql.TARGET_SCHEMA=DUMMY
databases.sql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_postgresql.USERNAME=postgres
databases.sql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_postgresql.USERPASSWORD=6OCfi1UFXZPb6Ai2DB9H5/MTFnuuQ3eSG4DXTjVIhS+hAPC0G4jTm/4DKjLII9GIsDyAHxIvaHba6EeRBYlvl2xAxv3mm2OE54uYnfYWW7M7BK24kHFxEv2F1wMJFL8t
databases.sql.folder.connectivity.folder.data\ sources.datasources.jdbc.ds_postgresql.USERPASSWORD.ENCRYPTED=ENCRYPTED
