databases.opc.folder.connector.folder.data\ sources.datasources.custom.opc_connector.Client\ Certificate\ Der\ Path.ROUTE.LOCAL.PATH=/opt/denodo/exports/dummy-cert.der
databases.opc.folder.connector.folder.data\ sources.datasources.custom.opc_connector.Client\ PrivateKey\ Pem\ Path.ROUTE.LOCAL.PATH=/opt/denodo/exports/dummy-key.pem
