users.basic_user.PASSWORD=A0LxfIgqTqprnUIeZ0THrvMPODf4QAY/aWQJ/EoBvWOv4wj64qqF5c6AL7xmWW7cUPh8UThFGMi4BvCpUrVX6wdhTVPjMPmx
users.basic_user.PASSWORD.ALGORITHM=SHA512
users.basic_user.PASSWORD.ENCRYPTED=ENCRYPTED
