users.chamelon.PASSWORD=qUy4mBjGMwkMSmcMrp+E4RwVYeqDKo7FHTuBBdvHzKubs5bnW0E3tzJQc8HbXNS68cmhbilKYpgtaJHYkvFwaoaysCRA7nGZ
users.chamelon.PASSWORD.ALGORITHM=SHA512
users.chamelon.PASSWORD.ENCRYPTED=ENCRYPTED
