users.new_user1.PASSWORD=wuuHt14r+BQ8zJxX5Sa6XXCLLSTP6XBC3BbJkgQdavEZRqC5t/XPwCbdl9vI+PThcyk37iyqE2v7iAQSQYcdAZPvGQam9sM1
users.new_user1.PASSWORD.ALGORITHM=SHA512
users.new_user1.PASSWORD.ENCRYPTED=ENCRYPTED
