users.new_user3.PASSWORD=wKndu0Isx5vn3Z1672G4ru9569N5nqtiLv4OQlw8Dt/Gd8bgLRF/gF2rpyTU0F+MuBI63+DoGiV0vFxUC3YHcw2Ppm93Bjla
users.new_user3.PASSWORD.ALGORITHM=SHA512
users.new_user3.PASSWORD.ENCRYPTED=ENCRYPTED
