users.new_user2.PASSWORD=k9JEXScSuWCSv2ImtTG1U1BCwbejZouKyCLEyX0pRpuayilIYuCAk4ZRNipqj66ZOYHrCrusPBfSa64FAVdV8Vy2a64d/G/e
users.new_user2.PASSWORD.ALGORITHM=SHA512
users.new_user2.PASSWORD.ENCRYPTED=ENCRYPTED
